---
title: "7C2-CT-4A Introduction to Open Data"
subtitle: "HEG-GE Bachelor Information Science | Spring Semester 2024-2025"
authors: 
  - name: Julien A. Raemy
    orcid: 0000-0002-4711-5759
    email: julien.raemy@bar.admin.ch
    affiliations:
      - Swiss Federal Archives
date: "2025-01-19"
date-modified: last-modified
license: "CC BY"
---


# About 

## About this Website

This website represents the second iteration of the *Introduction to Open Data* course, evolving from its initial form as a Markdown-based presentation [@raemyintroduction2024].

While the original presentation provided a solid foundation, a website proved to be a more suitable medium for this topic. This Quarto-based site builds on the original content while leveraging the strengths of a web format to provide an enriched and more accessible experience for readers as well as allowing for continuous updates.

## About the Instructor

[Dr. Julien A. Raemy](https://julsraemy.ch) is an Information Specialist and Digital Humanities Practitioner. He currently works as a Data Scientist at the Swiss Federal Archives. 

He holds a Bachelor's and Master’s degree in Information Science from the HES-SO University of Applied Sciences and Arts of Western Switzerland. He completed his PhD in Digital Humanities at the University of Basel in 2024, with a dissertation titled "Linked Open Usable Data for Cultural Heritage: Perspectives on Community Practices and Semantic Interoperability". His research examines how cultural heritage institutions can better share their digital collections through LOUD standards, particularly focusing on the International Image Interoperability Framework (IIIF) and Linked Art specifications. Through analysis of the PIA research project and Yale's Collections Discovery platform, his work investigates both the social dynamics of communities developing these standards and the technical challenges of making cultural data more interoperable.

Julien A. RAemy has worked extensively in academia and in or for the cultural heritage domain, including as a Photo Archivist for the Montreux Jazz Digital Project at the École Polytechnique Fédérale de Lausanne from 2015 to 2017, as a Research and Teaching Assistant at the Haute école de gestion de Genève from 2017 to 2021, and as an Interoperability Specialist at DaSCH, Swiss National Data and Service Center for the Humanities, from 2021 to 2024. He is also an active member of the IIIF and Linked Art communities.

## Host Institution

This course is held at:

Haute école de gestion de Genève (HEG-GE) <br />
Campus Battelle <br />
Rue de la Tambourine 17 <br />
CH-1227 Carouge <br />
Switzerland

## References