---
title: "7C2-CT-4A Introduction to Open Data"
subtitle: "HEG-GE Bachelor Information Science | Spring Semester 2024-2025"
authors: 
  - name: Julien A. Raemy
    orcid: 0000-0002-4711-5759
    email: julien.raemy@hesge.ch
    affiliations:
      - Swiss Federal Archives
      - University of Bern
date: "2025-01-19"
date-modified: last-modified
license: "CC BY"
---

# Introduction to Open Data

The course is designed for undergraduate students in Information Science at the HES-SO University of Applied Sciences and Arts of Western Switzerland, [Haute école de gestion de Genève (HEG-GE)](https://hesge.ch/heg/). It provides a comprehensive introduction to Open Data, covering key aspects such as:

- [Characteristics of Open Data](sections/characteristics.qmd)
- [Associated Movements](sections/movements.qmd)
- [Associated Principles](sections/principles.qmd)
- [Open Data Platforms and Organisations](sections/platforms.qmd)
- [Assessment, Data Quality, and Best Practices](sections/assessment.qmd)
- [Techniques, Software, and Tools](sections/techniques.qmd)
- [Showcases](sections/showcases.qmd)

## Why Open Data matters... TL;DR

### Public Engagement and Empowerment

- Open data empowers the public by providing access to information that was previously inaccessible or difficult to obtain.
- This fosters a more informed citizenry and enables individuals and communities to participate actively in civic and cultural discourses.

### Transparency and Accountability

- Open data enhances transparency and accountability, particularly in sectors where public trust is paramount.
- By making data freely accessible, open data initiatives allow for greater scrutiny and analysis, leading to more accountable governance and institutional practices.

### The Evolution of Open Data

- While open data in itself is a commendable goal, the concept of Linked Open (Usable) Data takes it a step further.
- Linked Open Data enhances the value of open data by ensuring it is not only available but also interconnected, making it more discoverable and useful for a wider range of applications and analyses.
- LOUD is about enhancing usability and semantic interoperability leveraging community-driven standards and practices.

### OGD and ORD for GLAM institutions

- Open Research Data (ORD) and Open Government Data (OGD) can be viewed both as a service provided to the public and as a process that requires active management and continuous improvement.
- Institutions in the GLAM (Galleries, Libraries, Archives, Museums) sector need to consider how these open data initiatives fit within their practices, both in terms of contributing data and utilising data for research, curation, and public engagement.

### AI and Machine Learning

- Open (and structured) data is crucial for Artificial Intelligence (AI) and Machine Learning (ML) systems, providing the large datasets necessary for training models.
- The availability of diverse, high-quality open datasets enables more robust and inclusive AI developments.
- Open data promotes transparency and ethical practices in AI by ensuring external validation and --- hopefully --- reducing biases.

### Collaboration is Key

- Collaboration is a fundamental aspect of open data initiatives.
  - Discussing best practices grounded in collaboration, such as leveraging the Collections as Data checklist.
  - Participating in the International Image Interoperability Framework (IIIF) and Linked Art communities for the cultural heritage field (and beyond, notably for the STEM --- Science, Technology, Engineering, and Mathematics --- sector).
  - OGD meet-ups (Open Data Beer).
- Such collaboration is vital for addressing global challenges, encouraging innovation, and ensuring the sustainable development of open data ecosystems.

## A multitude of tools

> For a better understanding of the past, <br/>
Our images have to be enhanced, <br/>
A new dialogue in three dimensions, <br/>
Must have openness at its heart, <br/>
For somewhere within the archive <br/>
Of our aggregated minds <br/>
Are a multitude of questions <br/>
And a multitude of answers, <br/>
Simply awaiting to be found.

<iframe width="560" height="315" src="https://www.youtube.com/embed/pOX9CrvAG7I?si=yLI8p4AMm0kCsk0y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

@mrgeeDayClosingMultitude2023, Data Poet at EuropeanaTech 2023
